import Layout from "@/components/global/Layout";
import ColumnPageView from "@/views/column";
import Head from "next/head";
import React from "react";

const Columns: React.FC = () => {
	return (
		<Layout>
			<Head>
				<title>Health App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ColumnPageView />
		</Layout>
	);
};

export default Columns;
