import Head from "next/head";
import Layout from "@/components/global/Layout";
import useWindowSize from "@/hook/useWindowSize";
import { Colors } from "@/theme/colors";

export default function Home() {
	const size = useWindowSize();
	return (
		<>
			<Head>
				<title>Health App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div
					style={{
						height: size.height - 270,
						color: Colors.primary[300],
						textAlign: "center",
					}}
				>
					<h1>こんにちは</h1>
				</div>
			</Layout>
		</>
	);
}
