import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/global/Layout";
import PrimaryButton from "@/components/common/button/LinearButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Health App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<h1>六角形メニュー用</h1>
			</Layout>
		</>
	);
}
