import Layout from "@/components/global/Layout";
import useWindowSize from "@/hook/useWindowSize";
import { Colors } from "@/theme/colors";
import { LOGIN_STORAGE_KEY, setStorage } from "@/utils/storage";
import Head from "next/head";
import { useState } from "react";

// Mock API function
function login(username: string, password: string): Promise<boolean> {
	return new Promise((resolve) => {
		setTimeout(() => {
			resolve(username === "admin" && password === "admin");
		}, 1000);
	});
}

export default function Login() {
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState("");
	const size = useWindowSize();

	async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
		event.preventDefault();
		setLoading(true);

		try {
			const success = await login(username, password);
			if (success) {
				setStorage(LOGIN_STORAGE_KEY, true);
				window.location.replace("/top");
			} else {
				setError("Invalid username or password");
			}
		} catch (error) {
			setError("An error occurred. Please try again later.");
		}

		setLoading(false);
	}

	return (
		<Layout>
			<Head>
				<title>Health App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				style={{
					display: "flex",
					flex: 1,
					height: size.height - 48 - 192,
					alignItems: "center",
					flexDirection: "column",
					color: Colors.dark[500],
					// backgroundColor: Colors.gray[400],
				}}
			>
				<h1>Login</h1>
				<form onSubmit={handleSubmit}>
					<div
						style={{
							width: 250,
						}}
					>
						<label>
							Username:
							<input
								style={{ width: "100%" }}
								type="text"
								value={username}
								onChange={(event) => setUsername(event.target.value)}
							/>
						</label>
					</div>
					<br />
					<div style={{ width: 250 }}>
						<label>
							Password:
							<input
								style={{ width: "100%" }}
								type="password"
								value={password}
								onChange={(event) => setPassword(event.target.value)}
							/>
						</label>
					</div>
					<br />
					<button
						type="submit"
						disabled={loading}
						style={{
							width: 258,
							color: Colors.light,
							backgroundColor: Colors.primary[400],
						}}
					>
						{loading ? "Loading..." : "Login"}
					</button>
					{error && <div style={{ color: "red" }}>{error}</div>}
				</form>
				<div style={{ marginTop: 64 }}>
					<i>Note: username: admin, password: admin</i>
				</div>
			</div>
		</Layout>
	);
}
